# Generated by Django 5.0.1 on 2024-01-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_list', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=155)),
                ('description', models.CharField(max_length=510)),
                ('status', models.CharField(max_length=10)),
                ('removed', models.BooleanField(default=False)),
                ('due_date', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
    ]
