# Generated by Django 5.0.1 on 2024-01-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('done', 'Done'), ('doing', 'Doing')], default='todo', max_length=10),
        ),
    ]
