# Generated by Django 5.0.1 on 2024-01-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_task_date_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_list',
            field=models.CharField(default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=510),
        ),
    ]
