# Generated by Django 5.0.1 on 2024-01-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_custom_list_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_list', models.CharField(default='', max_length=155)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_list',
        ),
    ]
