# Generated by Django 5.0.1 on 2024-01-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_customlist_remove_task_custom_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customlist',
            name='custom_list',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
