# Generated by Django 5.0.1 on 2024-01-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_due_date_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
