# Generated by Django 5.0.1 on 2024-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlist',
            name='custom_list',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
